stages:
  - build
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o app .


deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker build -t app .
    - docker run app

