stages:
  - build
  - package  
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o app .

package:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push samuelrak/trello-gl:latest

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull samuelrak/trello-gl:latest
    - docker run dockerfile

