stages:
  - build
  - run

build:
 stage: build
 image: docker:latest
 services:
    - docker:dind 
 script:
    - docker build -t dockerfile -f Dockerfile .

run:
  stage: run
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run -p 8080:8080 dockerfile /app/main
