stages:
  - build
  - deploy

build:
  stage: build
  image: docker:dind
  services:
    - docker:dind
  script:
    - docker build -t dockerfile .


deploy:
  stage: deploy
  image: docker:dind
  services:
    - docker:dind
  script:
    - docker run dockerfile

