stages:
  - build
  - test 
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o app .
    - docker build -t app .

test:
  stage: test
  script:
    - go test ./..

deploy:
  stage: deploy
  script:
    - docker run app

