stages:
  - build
  - run

build:
 stage: build
 image: docker:2.10.5   
 script:
    - docker build -t dockerfile -f Dockerfile .

run:
  stage: run
  image: docker:2.10.5
  script:
    - docker run -p 8080:8080 dockerfile
