stages:
  - build
  - test 
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o app .

test:
  stage: test
  image: docker:latest
  script:
    - go test ./..

deploy:
  stage: deploy
  image: docker:latest
    - docker run dockerfile

