stages:
  - build
  - test 
  - deploy

build:
  stage: build
  image: golang:latest
  script:
    - go build -o app .

package:
  stage: test
  script:
    - ./..

deploy:
  stage: deploy
    - docker run dockerfile

