version: "3.8"
services:
  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongodbdata:/data/db:cached

  app:
    image: go3
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27018
      - MONGO_DB=mydatabase
      - MONGO_USERNAME=mareklescinsky
      - MONGO_PASSWORD=EUFZTs6jcdkqqEUk

volumes:
  mongodbdata:
    external: true

