version: "3.8"
services:

  front-end:
    image: web
#    build: front-end/
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ./dist:/app/dist
    environment:
      - BACKEND_URL=http://localhost:8080

        #  mongodb:
        #    image: mongo:4.4
        #    restart: always
        #    ports:
        #      - 27017:27017
        #    volumes:
        #      - mongodbdata:/data/db:cached

  back-end:
 #   build: back-end/
    image: go
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27018
      - MONGO_DB=mydatabase
      - MONGO_USERNAME=mareklescinsky
      - MONGO_PASSWORD=EUFZTs6jcdkqqEUk

volumes:
  mongodbdata:
    external: true

